apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mongo
  name: mongo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate    
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - args:
        - --auth
        image: docker.io/mongo
        imagePullPolicy: Always
        name: mongo  
        ports:  
        - containerPort:  27017
          protocol: TCP
        volumeMounts:
          - name:  mongo-persistent-storage
          mountPath:  /data/db
        terminationMessagePath : /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name:  mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-volumeclaim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30        
          
